// Generated by `blume translate` — edit the default locale's meta file
// and rerun the translation instead of editing this copy.
export default {
  order: 5,
  pages: [
    "metadata",
    "open-graph",
    "structured-data",
    "rss",
    "sitemap-and-robots",
    "llms-txt",
    "markdown",
    "json-api",
    "mcp",
    "agent-discovery",
  ],
  title: "Auffindbarkeit",
};
